# Generated by Django 3.2.9 on 2021-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotasks',
            name='hellotask',
            field=models.TextField(),
        ),
    ]
